version: '3'

services:
  source_postgres:
    image: postgres:15
    # image: postgres:9.2
    ports:
      - "5433:5432"
    networks:
      - elt_network
    environment:
      POSTGRES_DB: source_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - ./source_db_init/init.sql:/docker-entrypoint-initdb.d/init.sql

  destination_postgres:
    image: postgres:15
    # image: postgres:9.2
    ports:
      - "5434:5432"
    networks:
      - elt_network
    environment:
      POSTGRES_DB: destination_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret

  elt_script:
    build:
      context: ./elt_script
      dockerfile: Dockerfile
    command: ["python", "elt_script.py"]
    networks:
      - elt_network
    depends_on:
      - source_postgres
      - destination_postgres
    healthcheck:
      test: ["CMD-SHELL", "echo 'ELT script completed'"]
      interval: 5s
      retries: 5
      start_period: 5s

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.4.7
    command:
      [
        "run",
        "--profiles-dir",
        "/profiles",
        "--project-dir",
        "/custom_postgres"
      ]
    networks:
      - elt_network
    volumes:
      - ./custom_postgres:/custom_postgres
      - ./profiles:/profiles
    depends_on:
      elt_script:
        condition: service_healthy
    environment:
      DBT_PROFILE: default
      DBT_TARGET: dev

networks:
  elt_network:
    driver: bridge
